name: 'Setup Bun and Install'
description: 'Bun 설치 및 의존성 설치를 수행하는 공통 액션 (캐싱 포함)'

inputs:
  bun-version:
    description: 'Bun 버전'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: bun-${{ runner.os }}-${{ hashFiles('bun.lock') }}
        restore-keys: |
          bun-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: bun install
