name: "\U0001F4DD 문서 요청"
description: AI가 작성할 새 문서를 요청합니다
title: "[요청] "
labels: ["request"]
body:
  - type: markdown
    attributes:
      value: |
        AI가 문서 초안을 자동으로 작성합니다. 요청 내용을 상세히 작성해주세요.

  - type: input
    id: doc_title
    attributes:
      label: 문서 제목
      description: 작성을 원하는 문서의 제목
      placeholder: 예) Kubernetes 배포 가이드
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 문서 내용 설명
      description: 문서에 포함되어야 할 내용을 설명해주세요
      placeholder: |
        어떤 내용이 포함되어야 하나요?
        대상 독자는 누구인가요?
        참고할 자료가 있나요?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 카테고리
      description: 문서의 카테고리를 선택해주세요
      options:
        - 가이드
        - API 문서
        - 튜토리얼
        - 참조
        - 기타
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 추가 정보
      description: 참고 자료, 링크, 기타 요청사항
      placeholder: 선택 사항입니다
