name: 'Git Commit and Push'
description: '변경사항 커밋 및 푸시를 수행하는 공통 액션'

inputs:
  message:
    description: '커밋 메시지'
    required: true
  user-email:
    description: 'Git 사용자 이메일'
    required: false
    default: 'action@github.com'
  user-name:
    description: 'Git 사용자 이름'
    required: false
    default: 'GitHub Action'

outputs:
  has_changes:
    description: '변경사항 존재 여부'
    value: ${{ steps.commit.outputs.has_changes }}

runs:
  using: 'composite'
  steps:
    - name: Commit and push
      id: commit
      shell: bash
      env:
        HUSKY: '0'
      run: |
        git config --local user.email "${{ inputs.user-email }}"
        git config --local user.name "${{ inputs.user-name }}"
        git add -A
        if git diff --staged --quiet; then
          echo "변경 사항 없음"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          git commit -m "${{ inputs.message }}"
          git pull --rebase
          git push
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi
